### ISSUE TITLE
Cleanup Screenshots

### ISSUE THREAD

**Issue by mjuvekar7** [Terasology/AdditionalWorlds#17]
Currently there are a bunch of images in the `screenshots` directory of this repository. This needs to be changed as it could potentially cause the module to become huge because of the unnecessary bloat of the images.
A possible fix for this is to move all images to an image hosting service and keep the links in the README or a separate file.

**Comment by SurajDatta** [comment]
I can try working on this.. :)

**Comment by skaldarnar** [comment]
Done by https://github.com/Terasology/AdditionalWorlds/commit/b3ec88b99675744f3d6cb190767de6de7d885ffb
